// ============= Exercise Info Data =============
const exerciseInfo = {
  smoothPursuit: {
    icon: '🔵', title: 'Smooth Pursuit (부드러운 추적)',
    distance: '50~70cm (팔 길이, 일반 모니터 거리)',
    mechanism: '눈에는 물체를 부드럽게 따라가는 "추적 시스템(smooth pursuit system)"이 있습니다. 이 시스템은 움직이는 물체의 이미지를 망막 중심(중심와, fovea)에 계속 유지시키는 역할을 합니다.',
    benefits: [
      '안구 추적 정확도 향상 — 움직이는 물체를 놓치지 않고 따라가는 능력 개선',
      '내직근 & 외직근 협응력 강화 — 좌우 수평 추적의 부드러움 향상',
      '읽기 능력 개선 — 텍스트를 따라가는 안구 움직임이 더 안정적으로',
      '운전/스포츠 시 움직이는 물체 인지 능력 향상',
    ],
    muscles: ['내직근(Medial Rectus)', '외직근(Lateral Rectus)', '상직근(Superior Rectus)', '하직근(Inferior Rectus)'],
    tip: '머리를 고정하고 눈만 움직이세요. 점을 놓치지 않고 부드럽게 따라가는 것이 핵심입니다.',
  },
  figure8: {
    icon: '♾️', title: 'Figure 8 (무한대 패턴)',
    distance: '50~70cm (팔 길이)',
    mechanism: '무한대(∞) 패턴은 눈의 6개 외안근을 모든 방향으로 골고루 사용하는 궤적입니다. 수평, 수직, 대각선 운동이 자연스럽게 조합됩니다.',
    benefits: [
      '6개 외안근의 균형 있는 강화',
      '안구 운동 범위(ROM) 확대',
      '좌우 뇌 반구 연결 강화',
      '안구 근육 유연성 향상',
    ],
    muscles: ['내직근', '외직근', '상직근', '하직근', '상사근(Superior Oblique)', '하사근(Inferior Oblique)'],
    tip: '무한대 모양의 교차점(중앙)을 지날 때 시선이 흔들리지 않도록 집중하세요.',
  },
  saccade: {
    icon: '⚡', title: 'Saccade Training (빠른 시선 이동)',
    distance: '50~70cm (팔 길이)',
    mechanism: 'Saccade는 시선을 한 지점에서 다른 지점으로 빠르게 점프시키는 안구 운동입니다. 읽기, 운전, 스포츠 등 일상에서 가장 많이 사용되는 유형입니다.',
    benefits: [
      '시선 이동 속도 & 정확도 향상',
      '읽기 속도 향상',
      '시각적 탐색 능력 강화',
      '반응 시간 단축',
    ],
    muscles: ['내직근', '외직근', '상직근', '하직근'],
    tip: '점이 나타나면 최대한 빠르게 시선을 이동하되, 정확하게 점 위에 초점을 맞추세요.',
  },
  hPattern: {
    icon: '🔷', title: 'H-Pattern (H자 패턴)',
    distance: '50~70cm (팔 길이)',
    mechanism: 'H-Pattern은 안과 검사에서 6개 외안근의 기능을 평가할 때 사용하는 표준 패턴입니다.',
    benefits: [
      '6개 외안근 체계적 강화',
      '안구 근육 불균형 개선',
      '사위(phoria) 예방',
      '대각선 추적 능력 향상',
    ],
    muscles: ['내직근', '외직근', '상직근', '하직근', '상사근', '하사근'],
    tip: 'H자의 꼭짓점에서 잠깐 멈추며 초점을 확인하세요.',
  },
  speedReading: {
    icon: '📖', title: 'Speed Reading (속독 눈운동)',
    distance: '40~60cm (독서 거리)',
    mechanism: '속독의 핵심은 한 번의 고정(fixation)으로 더 넓은 범위의 글자를 인식하는 것입니다. 주변 시야(peripheral vision)의 인식 범위를 점진적으로 확장합니다.',
    benefits: [
      '읽기 속도 향상',
      '주변 시야(peripheral vision) 확장',
      '고정 횟수(fixation count) 감소',
      '되돌아 읽기(regression) 감소',
      '집중력 향상',
    ],
    muscles: ['내직근(좌→우 이동)', '외직근(좌→우 이동)'],
    tip: '포인터를 따라가되, 포인터 주변의 넓은 범위를 의식적으로 인지하려고 노력하세요.',
  },
  dynamicAcuity: {
    icon: '🎯', title: 'Dynamic Visual Acuity (동체시력)',
    distance: '50~70cm (팔 길이)',
    mechanism: '동체시력은 움직이는 물체의 세부 사항을 인식하는 능력입니다. 뇌의 시각 처리 속도와 안구 추적 시스템의 협응이 필요합니다.',
    benefits: [
      '동체시력 향상',
      '시각 처리 속도 증가',
      '스포츠 퍼포먼스 향상',
      '운전 안전성 향상',
      '순간 인지력(flash recognition) 강화',
    ],
    muscles: ['내직근', '외직근', '상직근', '하직근', '시각피질(Visual Cortex)'],
    tip: '움직이는 글자를 눈으로 추적하면서 읽으세요. 속도가 빨라질수록 집중력을 높이세요.',
  },
  visualSpan: {
    icon: '🔍', title: 'Visual Span (시폭 확장)',
    distance: '40~60cm',
    mechanism: '중앙 고정점(fixation point)에 시선을 고정한 채, 주변부에 나타나는 자극을 인식하는 훈련. 속독의 핵심 능력인 "한 눈에 볼 수 있는 글자 수"를 늘리는 기초 훈련입니다.',
    benefits: [
      '시폭(visual span) 확장',
      '속독 능력 향상 기초',
      '주변시야 해상도 향상',
      '한 번의 고정으로 인식하는 정보량 증가',
    ],
    muscles: ['망막 주변부(Peripheral Retina)', '시각피질(Visual Cortex)'],
    tip: '반드시 중앙의 십자(+) 표시에서 시선을 떼지 마세요. 주변 시야로 인식하는 것이 핵심입니다.',
  },
  peripheralDetection: {
    icon: '👁️', title: 'Peripheral Detection (주변시야 감지)',
    distance: '50~70cm',
    mechanism: '중앙에 시선을 고정한 상태에서 시야 가장자리에 나타나는 자극을 감지하는 훈련. 망막 주변부의 감도를 높이고, 뇌의 시각 주의 분배 능력을 강화합니다.',
    benefits: [
      '주변시야 감도 향상',
      '운전 시 측면 위험 감지 능력 향상',
      '스포츠 시야 확장',
      '시각적 주의력 분배 능력 강화',
    ],
    muscles: ['망막 주변부', '시각피질', '주의 네트워크(Attention Network)'],
    tip: '중앙의 점에서 절대 시선을 떼지 마세요. 주변에서 무언가 번쩍이는 것을 감지하세요.',
  },
  zigzagTracking: {
    icon: '⚡', title: 'Zigzag Tracking (지그재그 추적)',
    distance: '50~70cm',
    mechanism: '대각선+수평이 결합된 지그재그 패턴은 수직과 수평 근육이 동시에 협응해야 하므로, 복합적인 근육 협응 훈련이 됩니다.',
    benefits: [
      '복합 방향 안구 근육 협응 강화',
      '읽기 시 줄 바꿈 추적 능력 향상',
      '대각선 시선 이동의 부드러움 개선',
      '수직+수평 근육 동시 훈련',
    ],
    muscles: ['내직근', '외직근', '상직근', '하직근 (복합 협응)'],
    tip: '지그재그 꺾이는 지점에서 시선이 튕기지 않도록 부드럽게 전환하세요.',
  },
  schulteTable: {
    icon: '🔢', title: 'Schulte Table (슐테 테이블)',
    distance: '40~60cm',
    mechanism: '5×5 격자에 랜덤 배치된 1~25 숫자를 순서대로 찾는 훈련입니다. 시선을 중앙에 고정한 채 주변시(peripheral vision)만으로 숫자를 찾아야 합니다. 속독 훈련의 가장 기본적이고 대표적인 방법입니다.',
    benefits: [
      '시각 주의 범위 47% 향상 (8주 훈련 연구)',
      '주변시야 활용 능력 극대화',
      '시각적 탐색 속도 향상',
      '집중력 및 작업 기억력 강화',
    ],
    muscles: ['망막 주변부', '시각피질', '전두엽 주의 네트워크'],
    tip: '격자 중앙에 시선을 고정하세요. 눈을 움직여 숫자를 찾으면 훈련 효과가 떨어집니다. 주변시로 찾는 것이 핵심입니다.',
  },
  rsvp: {
    icon: '⚡', title: 'RSVP (빠른 순차 시각 제시)',
    distance: '40~60cm (독서 거리)',
    mechanism: 'RSVP(Rapid Serial Visual Presentation)는 화면 정중앙에 단어를 하나씩 빠르게 표시하여, 눈 이동 없이 읽기 속도를 높이는 훈련입니다. ORP(Optimal Recognition Point)를 빨간색으로 강조하여 단어 인식을 돕습니다.',
    benefits: [
      '읽기 속도 대폭 향상 (250→500+ WPM)',
      '눈 이동 제거로 에너지 절약',
      '내면 발성(subvocalization) 억제 훈련',
      '시각적 정보 처리 속도 향상',
    ],
    muscles: ['시각피질', '언어 처리 영역'],
    tip: '빨간색으로 강조된 글자(ORP)에 시선을 고정하세요. 머릿속으로 발음하지 말고 "보기만" 하세요.',
  },
  tachistoscope: {
    icon: '📸', title: 'Tachistoscope (순간 노출 인식)',
    distance: '50~70cm',
    mechanism: '단어/숫자가 극히 짧은 시간(0.8초→0.08초)동안 화면에 번쩍 나타납니다. 시간이 지날수록 노출 시간이 짧아지고 내용이 복잡해지며, 순간 인지력과 시각 처리 속도를 극한까지 훈련합니다.',
    benefits: [
      '순간 인지력 극대화',
      '시각 정보 처리 속도 향상',
      '단어/숫자 즉시 인식 능력 강화',
      '집중력 향상',
    ],
    muscles: ['시각피질', '작업 기억(Working Memory)'],
    tip: '번쩍이는 내용을 놓치지 않으려고 하세요. 잠시 후 정답이 표시되니 자신의 인식과 비교해보세요.',
  },
  eyeHop: {
    icon: '👀', title: 'Eye-Hop (아이홉 청킹 훈련)',
    distance: '40~60cm (독서 거리)',
    mechanism: '텍스트를 2개 열(column)로 배치하고, 왼쪽→오른쪽으로 시선을 "홉(hop)"하며 읽습니다. 단어 하나씩이 아니라 단어 그룹(chunk) 단위로 고정점을 잡는 습관을 형성하여, 한 줄을 읽는 데 필요한 눈 고정 횟수를 줄입니다.',
    benefits: [
      '고정점(fixation) 수 감소로 읽기 속도 향상',
      '청킹(chunking) 습관 형성',
      '좌우 시선 홉 정확도 향상',
      '실전 독서에 직접 적용 가능한 훈련',
    ],
    muscles: ['내직근', '외직근', '시각피질'],
    tip: '초록색 점(fixation point)에 시선을 맞추고, 그 주변 단어들을 한꺼번에 인식하세요.',
  },
  nearFar: {
    icon: '🔭', title: 'Near-Far Focus (원근 초점)',
    distance: '화면: 40~50cm ↔ 먼 곳: 3~6m 이상',
    mechanism: '모양체근(ciliary muscle)은 수정체의 두께를 조절하여 초점 거리를 변경합니다. 실제로 가까운 곳과 먼 곳을 번갈아 보면서 모양체근의 유연성을 회복합니다.',
    benefits: [
      '모양체근 유연성 회복',
      '조절 경련 완화',
      '디지털 눈 피로 감소',
      '가성근시 예방',
    ],
    muscles: ['모양체근(Ciliary Muscle)', '내직근(수렴 시)'],
    tip: '시작 전 3~6m 떨어진 곳에 초점을 맞출 물체를 정하세요.',
  },
  rule202020: {
    icon: '⏱️', title: '20-20-20 Rule',
    distance: '작업 시: 50~70cm → 쉬는 시간: 6m 이상',
    mechanism: '20분마다 20피트(6m) 먼 곳을 20초간 보면, 모양체근이 이완되고 눈 깜빡임이 회복됩니다.',
    benefits: [
      '디지털 눈 피로 예방 (AAO 공식 권장)',
      '안구 건조증 완화',
      '모양체근 주기적 이완',
      '두통 & 목 통증 감소',
    ],
    muscles: ['모양체근(이완)'],
    tip: '창 밖의 건물이나 나무 등 먼 곳의 물체에 초점을 맞추세요.',
  },
  blinkTraining: {
    icon: '😌', title: 'Blink Training (깜빡임 훈련)',
    distance: '상관없음',
    mechanism: '화면을 볼 때 눈 깜빡임이 정상의 절반 이하로 줄어들어 안구 건조가 발생합니다. 의식적으로 규칙적인 깜빡임 리듬을 훈련합니다.',
    benefits: [
      '안구 건조증 예방 및 완화',
      '눈물막 안정성 향상',
      '화면 작업 시 깜빡임 빈도 정상화',
    ],
    muscles: ['안륜근(Orbicularis Oculi)', '눈꺼풀올림근(Levator Palpebrae)'],
    tip: '완전히 눈을 감았다가 뜨는 것이 중요합니다 (반쯤 감는 것은 효과 없음).',
  },
  eyeRelaxation: {
    icon: '🧘', title: 'Eye Relaxation (눈 이완)',
    distance: '상관없음 (눈을 감는 운동)',
    mechanism: '팔밍(palming)은 손바닥으로 눈을 가볍게 덮어 완전한 암흑 상태를 만들어, 망막과 시각피질이 완전히 쉬게 합니다. 복식호흡과 결합하면 부교감신경이 활성화됩니다.',
    benefits: [
      '시각 피로 즉각 완화',
      '안구 근육 이완',
      '안압 감소 효과',
      '스트레스 관련 시력 저하 예방',
    ],
    muscles: ['모양체근(이완)', '외안근(이완)', '안륜근(이완)'],
    tip: '손바닥을 비벼 따뜻하게 한 후 눈 위에 올리세요. 눈알을 누르지 말고 가볍게 덮기만 하세요.',
  },
  bouncingBall: {
    icon: '🏀', title: 'Bouncing Ball (바운싱 볼)',
    distance: '50~70cm',
    mechanism: '물리 엔진 기반으로 여러 공이 화면 안에서 튕기며 서로 충돌합니다. 빛나는 타겟 공을 지속적으로 추적하면서, 주변의 방해 공들 사이에서 집중력을 유지해야 합니다. 실제 물체 추적과 유사한 상황을 시뮬레이션합니다.',
    benefits: [
      '실전적 물체 추적 능력 향상',
      '분산된 환경에서 집중 추적 능력 강화',
      '예측 불가능한 움직임에 대한 적응력 향상',
      '안구 추적 시스템(smooth pursuit)의 반응성 개선',
    ],
    muscles: ['내직근', '외직근', '상직근', '하직근', '시각피질'],
    tip: '빛나는 공에만 집중하세요. 다른 공과 충돌할 때 시선을 놓치지 않는 것이 핵심입니다.',
  },
  mot: {
    icon: '🎯', title: 'Multiple Object Tracking (다중 객체 추적)',
    distance: '50~70cm',
    mechanism: 'MOT(Multiple Object Tracking)는 스포츠 비전 과학에서 개발된 대표적인 시각 주의력 훈련 패러다임입니다. 여러 타겟을 동시에 추적하면서 뇌의 시각 주의 분배 능력과 작업 기억력을 강화합니다.',
    benefits: [
      '분할 주의력(divided attention) 향상',
      '시각적 작업 기억(visual working memory) 강화',
      '스포츠에서 여러 선수/공을 동시에 인지하는 능력 향상',
      '운전 시 다중 위험 요소 감지 능력 향상',
      '주의 용량(attentional capacity) 확장',
    ],
    muscles: ['시각피질', '전두엽 주의 네트워크', '두정엽(Parietal Lobe)'],
    tip: '타겟을 외울 때 위치 관계(삼각형, 직선 등)를 이용하면 추적이 쉬워집니다. 하나씩 보지 말고 전체를 한 눈에 담으세요.',
  },
  spiralPursuit: {
    icon: '🌀', title: 'Spiral Pursuit (나선 추적)',
    distance: '50~70cm',
    mechanism: '나선형 궤적은 수평·수직·대각선 운동이 연속적으로 결합된 복합 패턴입니다. 반지름이 계속 변하면서 눈의 추적 범위가 점진적으로 확대/축소되어, 6개 외안근을 균형 있게 훈련합니다.',
    benefits: [
      '전방위 안구 근육 균형 강화',
      '추적 범위 점진적 확장',
      '곡선 추적 정확도 향상',
      '안구 근육 유연성 및 지구력 향상',
      '최면적 패턴으로 집중력 자연스럽게 유도',
    ],
    muscles: ['내직근', '외직근', '상직근', '하직근', '상사근', '하사근'],
    tip: '점이 중심으로 돌아올 때와 바깥으로 나갈 때 모두 놓치지 않도록 부드럽게 따라가세요.',
  },
  reactionFlash: {
    icon: '💥', title: 'Reaction Flash (반응 플래시)',
    distance: '50~70cm',
    mechanism: '화면의 랜덤 위치에 다양한 도형(원, 다이아몬드, 링, 십자)이 짧은 시간 번쩍입니다. 점점 빠르게 나타나는 도형들을 눈으로 포착하면서 시각 반응 속도와 시야 전체에 대한 주의력을 훈련합니다.',
    benefits: [
      '시각 반응 속도 향상',
      '시야 전체에 대한 경각심(alertness) 강화',
      '빠른 시선 이동(saccade) 정확도 개선',
      '스포츠/게임에서의 순간 반응 능력 향상',
    ],
    muscles: ['내직근', '외직근', '상직근', '하직근', '시각피질', '전두엽'],
    tip: '화면 전체를 넓게 바라보면서, 번쩍이는 도형이 나타나면 즉시 시선을 이동시키세요.',
  },
  colorTrail: {
    icon: '🎨', title: 'Color Trail (컬러 트레일)',
    distance: '50~70cm',
    mechanism: '여러 색상의 점들이 화면을 자유롭게 이동합니다. 지정된 색상의 점 하나만을 다른 점들 사이에서 선택적으로 추적해야 합니다. 시각적 선택 주의력(selective attention)과 색상 기반 필터링 능력을 훈련합니다.',
    benefits: [
      '선택적 시각 주의력 향상',
      '색상 기반 필터링 능력 강화',
      '방해 자극(distractor) 무시 능력 향상',
      '지속 주의력(sustained attention) 강화',
      '시각적 혼잡 환경에서의 추적 능력 향상',
    ],
    muscles: ['시각피질(V4 색상 영역)', '전두엽 주의 네트워크', '내직근', '외직근'],
    tip: '처음 3초간 대상 색상의 점 위치를 파악한 후, 시선을 고정하고 계속 추적하세요. 다른 색상의 점은 무시하세요.',
  },
  clockTracking: {
    icon: '🕐', title: 'Clock Tracking (시계 추적)',
    distance: '50~70cm',
    mechanism: '시계의 12포지션(12시, 1시, …, 11시)을 순서대로 따라가는 훈련입니다. 각 포지션에서 잠시 정지하므로, 정밀한 정지-이동 전환(stop-and-go saccade)을 훈련합니다.',
    benefits: [
      '정밀한 시선 정지-이동 전환 능력 향상',
      '12방향 균등한 안구 근육 훈련',
      '각도 인지 및 공간 감각 강화',
      '시선 고정(fixation) 안정성 향상',
    ],
    muscles: ['내직근', '외직근', '상직근', '하직근', '상사근', '하사근'],
    tip: '각 시계 위치에서 점이 잠시 멈출 때, 정확히 초점을 맞추세요. 머리를 돌리지 말고 눈만 움직이세요.',
  },
  diamondPattern: {
    icon: '💎', title: 'Diamond Pattern (다이아몬드 패턴)',
    distance: '50~70cm',
    mechanism: '다이아몬드(마름모) 형태의 4개 꼭짓점(상, 우, 하, 좌)을 따라 이동하는 패턴입니다. 수직과 수평이 아닌 대각선 방향의 시선 전환을 집중적으로 훈련합니다.',
    benefits: [
      '대각선 시선 전환 능력 강화',
      '상사근/하사근 집중 훈련',
      '수직-수평 전환의 부드러움 개선',
      '안구 근육 균형 향상',
    ],
    muscles: ['상직근', '하직근', '상사근', '하사근'],
    tip: '꼭짓점에서 방향이 바뀔 때 부드럽게 전환하세요. 대각선 이동 시 시선이 흔들리지 않도록 집중하세요.',
  },
  vergenceRock: {
    icon: '🔀', title: 'Vergence Rock (폭주/개산 훈련)',
    distance: '40~60cm',
    mechanism: '두 점이 가까워졌다 멀어지기를 반복합니다. 점이 가까워질 때 양눈이 안쪽으로 모이는 폭주(convergence)와, 멀어질 때 바깥으로 벌어지는 개산(divergence)을 교대로 훈련합니다.',
    benefits: [
      '폭주/개산 근육(내직근/외직근) 유연성 향상',
      '근거리 작업 시 눈 피로 감소',
      '양안 조절 협응(vergence-accommodation coupling) 강화',
      '사시 예방 및 폭주 부전(convergence insufficiency) 개선',
    ],
    muscles: ['내직근(Medial Rectus) — 폭주', '외직근(Lateral Rectus) — 개산'],
    tip: '두 점이 하나로 합쳐지는 순간을 느끼세요. 이중으로 보이기 시작하면 잠시 눈을 쉬었다 다시 시도하세요.',
  },
  circularPursuit: {
    icon: '🔄', title: 'Circular Pursuit (원형 추적)',
    distance: '50~70cm',
    mechanism: '원형 궤도를 따라 이동하는 점을 추적합니다. 원의 크기가 점차 확대/축소되고 방향이 전환되어, 전방위 추적 능력과 적응력을 동시에 훈련합니다.',
    benefits: [
      '전방위 안구 근육 균형 훈련',
      '가변 반경 추적으로 적응력 향상',
      '방향 전환 시 추적 연속성 유지 능력 강화',
      '원형 추적의 부드러움 개선',
    ],
    muscles: ['내직근', '외직근', '상직근', '하직근', '상사근', '하사근'],
    tip: '방향이 바뀌는 순간 시선을 놓치지 않도록 주의하세요. 원이 커질수록 시선 이동 범위도 넓어집니다.',
  },
  metronomeReading: {
    icon: '🎵', title: 'Metronome Reading (메트로놈 읽기)',
    distance: '40~60cm (독서 거리)',
    mechanism: '메트로놈 바가 텍스트 위를 일정한 속도로 지나갑니다. 바의 속도에 맞춰 읽기 페이스를 조절하는 훈련으로, 되돌아 읽기(regression)를 방지하고 일정한 읽기 리듬을 형성합니다.',
    benefits: [
      '읽기 속도의 일정한 페이싱 습관 형성',
      '되돌아 읽기(regression) 방지',
      '시선 이동의 리듬감 향상',
      '집중력 유지 능력 강화',
    ],
    muscles: ['내직근', '외직근', '시각피질'],
    tip: '바보다 앞서거나 뒤처지지 말고 정확히 바의 위치에 맞춰 읽으세요. 자연스러운 리듬을 유지하세요.',
  },
  numberFlash: {
    icon: '🔢', title: 'Number Flash (숫자 플래시)',
    distance: '50~70cm',
    mechanism: '점점 길어지는 숫자열이 짧은 시간 동안 화면에 표시됩니다. 순간적으로 노출된 숫자를 기억하고 입력하여, 시각 단기 기억(visual short-term memory)과 순간 인지력을 훈련합니다.',
    benefits: [
      '시각 단기 기억 용량 확장',
      '순간 인지력 향상',
      '숫자/문자 즉시 인식 능력 강화',
      '작업 기억(working memory) 향상',
    ],
    muscles: ['시각피질', '작업 기억(Working Memory)', '전두엽'],
    tip: '숫자를 하나씩 읽으려 하지 말고, 전체 숫자열을 이미지로 한 번에 인식하려고 노력하세요.',
  },
  columnReading: {
    icon: '📄', title: 'Column Reading (컬럼 읽기)',
    distance: '40~60cm (독서 거리)',
    mechanism: '좁은 컬럼에 텍스트를 배치하여 수직 방향 시선 이동 위주의 읽기를 훈련합니다. 컬럼 너비가 점차 넓어지면서 수평 시선 이동량도 증가하여, 점진적으로 시폭을 확장합니다.',
    benefits: [
      '수직 시선 이동 읽기 능력 강화',
      '좁은 시폭에서 점진적 확장 훈련',
      '줄 바꿈 추적 정확도 향상',
      '집중적 읽기 습관 형성',
    ],
    muscles: ['상직근', '하직근', '내직근', '외직근'],
    tip: '컬럼 중앙에 시선을 고정하고, 좌우 끝 글자를 주변시로 인식하세요. 컬럼이 넓어질수록 더 넓은 시폭이 필요합니다.',
  },
  usefulFieldOfView: {
    icon: '🌐', title: 'Useful Field of View (유효 시야 훈련)',
    distance: '50~70cm',
    mechanism: 'UFOV(Useful Field of View)는 중심 과제(중앙 도형 식별)와 주변 과제(외곽 타겟 위치 식별)를 동시에 수행하는 이중 과제 패러다임입니다. 시야 전체에서 정보를 효과적으로 수집하는 능력을 훈련합니다.',
    benefits: [
      '유효 시야(UFOV) 확장',
      '운전 안전성 향상 (사고 위험 최대 50% 감소 연구)',
      '이중 과제 수행 능력 강화',
      '시각적 주의 분배 능력 향상',
    ],
    muscles: ['시각피질', '망막 주변부', '전두엽 주의 네트워크', '두정엽'],
    tip: '중앙 도형에 먼저 집중하되, 주변부에 나타나는 타겟도 놓치지 마세요. 두 과제를 동시에 수행하는 것이 핵심입니다.',
  },
  flankerTask: {
    icon: '➡️', title: 'Flanker Task (플랭커 과제)',
    distance: '50~70cm',
    mechanism: 'Eriksen Flanker Task는 인지심리학의 대표적 선택적 주의력 패러다임입니다. 중앙 화살표의 방향을 판별하면서, 양 옆의 방해 화살표(flanker)를 무시해야 합니다. 비일치(incongruent) 조건에서 반응 억제력을 훈련합니다.',
    benefits: [
      '선택적 주의력(selective attention) 향상',
      '반응 억제(response inhibition) 능력 강화',
      '방해 자극 필터링 능력 향상',
      '인지 갈등 해소 속도 향상',
    ],
    muscles: ['시각피질', '전두엽(전대상피질, ACC)', '주의 네트워크'],
    tip: '중앙 화살표에만 집중하세요. 양쪽 화살표가 반대 방향일 때 특히 정확도에 주의하세요.',
  },
  crowdingResistance: {
    icon: '🔤', title: 'Crowding Resistance (혼잡 저항 훈련)',
    distance: '50~70cm',
    mechanism: '시각적 혼잡(crowding)은 주변에 다른 자극이 밀집해 있을 때 타겟 인식이 어려워지는 현상입니다. 밀집된 글자 사이에서 중앙 타겟을 식별하는 훈련으로, 혼잡 저항력을 강화합니다.',
    benefits: [
      '시각적 혼잡 저항력 향상',
      '밀집 환경에서의 타겟 인식 능력 강화',
      '읽기 시 글자 간 간섭 감소',
      '주변시야 해상도 향상',
    ],
    muscles: ['시각피질(V1, V2)', '측두엽 문자 인식 영역'],
    tip: '중앙의 빨간 글자에만 집중하세요. 주변 글자에 의해 혼동되지 않도록 의식적으로 필터링하세요.',
  },
  attentionWindow: {
    icon: '🪟', title: 'Attention Window (주의 창 확장)',
    distance: '50~70cm',
    mechanism: '중앙 고정점을 기준으로 일정 반경 내의 글자만 표시됩니다. 반경이 점차 확장되면서, 한 번에 인식할 수 있는 주의 창(attention window)의 크기를 점진적으로 늘려갑니다.',
    benefits: [
      '주의 창(attention window) 크기 확장',
      '한 번의 고정으로 인식 가능한 범위 증가',
      '속독 기초 능력 강화',
      '시폭(visual span) 향상',
    ],
    muscles: ['시각피질', '망막 주변부', '주의 네트워크'],
    tip: '중앙 고정점에서 절대 시선을 떼지 마세요. 주의 창이 넓어질수록 주변 글자까지 의식적으로 인식하려 노력하세요.',
  },
  memoryFlash: {
    icon: '🧠', title: 'Memory Flash (기억 플래시)',
    distance: '50~70cm',
    mechanism: '격자에서 특정 셀들이 짧은 시간 동안 빛납니다. 빛난 위치를 기억한 후 정확히 터치/클릭하여, 시각 공간 작업 기억(visuospatial working memory)을 훈련합니다.',
    benefits: [
      '시각 공간 작업 기억 용량 확장',
      '순간 위치 기억 능력 향상',
      '시각적 패턴 인식 능력 강화',
      '주의력 및 집중력 향상',
    ],
    muscles: ['시각피질', '해마(Hippocampus)', '전두엽 작업 기억 영역'],
    tip: '빛나는 셀들의 패턴을 이미지로 기억하세요. 하나씩 외우려 하지 말고 전체 배치를 한 번에 파악하세요.',
  },
  antiSaccade: {
    icon: '🔃', title: 'Anti-Saccade (반대 시선 이동)',
    distance: '50~70cm',
    mechanism: 'Anti-saccade 과제는 시각 신호가 나타난 곳의 반대편을 바라보는 훈련입니다. 반사적 시선 이동(prosaccade)을 억제하고 의도적으로 반대 방향을 보는 것은, 전두엽의 억제 기능과 실행 기능을 강화합니다.',
    benefits: [
      '반사적 시선 이동 억제력 강화',
      '전두엽 실행 기능 향상',
      '충동 조절 능력 개선',
      '의도적 주의 전환 능력 강화',
    ],
    muscles: ['전두안야(Frontal Eye Field)', '전두엽 억제 영역', '내직근', '외직근'],
    tip: '신호가 나타나면 본능적으로 그쪽을 보지 말고, 반대편에 나타나는 타겟을 찾으세요. 처음에는 어렵지만 점차 빨라집니다.',
  },
  visualSearch: {
    icon: '🔎', title: 'Visual Search (시각 탐색)',
    distance: '50~70cm',
    mechanism: '다수의 방해 도형(distractor) 사이에서 특정 타겟 도형을 찾는 과제입니다. 효율적인 시각 탐색 전략과 pop-out 효과를 활용하여, 실생활에서의 시각적 검색 능력을 향상시킵니다.',
    benefits: [
      '시각 탐색 효율 향상',
      '방해 자극 중 타겟 검출 속도 향상',
      '시각적 주의력 범위 확장',
      '일상 생활에서의 물건 찾기 능력 향상',
    ],
    muscles: ['시각피질', '전두엽 주의 네트워크', '두정엽'],
    tip: '화면 전체를 체계적으로 스캔하세요. 한 곳에 오래 머물지 말고, 빠르게 넓은 영역을 훑어보세요.',
  },
  pencilPushup: {
    icon: '✏️', title: 'Pencil Push-up (연필 근접 수렴)',
    distance: '팔 길이 → 코끝 가까이',
    mechanism: '화면의 점이 점점 가까워지는 것을 시뮬레이션합니다. 실제로는 연필 끝을 눈 앞으로 가져오면서 양 눈의 폭주(convergence)를 극한까지 훈련하는 고전적 방법입니다. 폭주 부전(convergence insufficiency) 치료에 가장 널리 사용됩니다.',
    benefits: [
      '폭주 부전 개선 (CI 치료 1순위 운동)',
      '근거리 작업 지구력 향상',
      '양안시(binocular vision) 안정성 강화',
      '이중상(diplopia) 발생 지점 감소',
    ],
    muscles: ['내직근(Medial Rectus)', '모양체근(Ciliary Muscle)'],
    tip: '점이 커질 때 하나로 보이도록 집중하세요. 이중으로 보이기 시작하면 그 지점을 기억하세요 — 훈련이 진행되면 그 지점이 더 가까워집니다.',
  },
  eyeYoga: {
    icon: '🧘‍♂️', title: 'Eye Yoga (눈 요가)',
    distance: '상관없음 (눈만 움직이는 운동)',
    mechanism: '8방향(상, 우상, 우, 우하, 하, 좌하, 좌, 좌상)으로 순차적으로 시선을 이동하고 각 방향에서 수 초간 유지합니다. 요가의 드리스티(drishti, 시선 집중)와 유사하며, 모든 외안근을 체계적으로 스트레칭합니다.',
    benefits: [
      '6개 외안근 전체 스트레칭',
      '안구 근육 긴장 완화',
      '안구 운동 범위(ROM) 유지/확장',
      '안구 혈류 촉진',
    ],
    muscles: ['내직근', '외직근', '상직근', '하직근', '상사근', '하사근'],
    tip: '각 방향에서 최대한 끝까지 보고, 3초간 유지하세요. 통증이 있으면 무리하지 마세요.',
  },
  darkAdaptation: {
    icon: '🌙', title: 'Dark Adaptation (암순응 휴식)',
    distance: '상관없음 (화면이 어두워짐)',
    mechanism: '화면이 점진적으로 어두워지면서 완전한 암흑에 가까운 상태가 되고, 다시 천천히 밝아집니다. 망막의 간상세포(rod cells)가 어둠에 적응하는 암순응(dark adaptation) 과정을 유도하여, 디지털 기기 과다 노출로 지친 망막을 회복시킵니다.',
    benefits: [
      '망막 광수용체 회복',
      '디지털 눈 피로 완화',
      '간상세포 감도 회복',
      '전체적인 눈 이완 및 스트레스 해소',
    ],
    muscles: ['간상세포(Rod Cells)', '망막 색소 상피(RPE)', '동공 괄약근(이완)'],
    tip: '어두워지면 눈을 감아도 됩니다. 호흡에 집중하며 눈을 편안하게 쉬게 하세요. 밝아지기 시작하면 천천히 눈을 뜨세요.',
  },
};

function showInfo(type) {
  const info = exerciseInfo[type];
  if (!info) return;
  const ov = document.createElement('div');
  ov.className = 'info-modal-overlay';
  ov.onclick = (e) => { if (e.target === ov) ov.remove(); };
  ov.innerHTML = `
    <div class="info-modal">
      <button class="info-modal-close" onclick="this.closest('.info-modal-overlay').remove()">✕</button>
      <div class="info-icon">${info.icon}</div>
      <h2>${info.title}</h2>
      <h3>권장 시청 거리</h3>
      <div class="distance-badge">📏 ${info.distance}</div>
      <h3>어떻게 작동하나요?</h3>
      <p>${info.mechanism}</p>
      <h3>개선 효과</h3>
      <ul class="benefit-list">${info.benefits.map(b => `<li>${b}</li>`).join('')}</ul>
      <h3>관련 근육</h3>
      <div>${info.muscles.map(m => `<span class="muscle-tag">${m}</span>`).join('')}</div>
      <h3>운동 팁</h3>
      <p>${info.tip}</p>
    </div>
  `;
  document.body.appendChild(ov);
}
